source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.2' # (define required version)

pod 'PlayKit'
pod 'StreamrootSDK', '~> 3.12.0'
  
target 'PlayKit'
target 'PlayKit-Swift'
  
