source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.2' # (define required version)

# Change 'PlayKit' to 'DNAPlayKit' to integrate Streamroot's extended PlayKit
pod 'DNAPlayKit'
pod 'StreamrootSDK', '~> 3.12.0'
  
target 'PlayKit'
target 'PlayKit-Swift'
  
