source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.2' # (define required version)

pod 'PlayKit', :git => 'https://github.com/streamroot/playkit-ios', :branch => 'preferredForwardBufferDuration'
pod 'StreamrootSDK'
  
target 'PlayKit'
target 'PlayKit-Swift'
  
