source 'https://github.com/CocoaPods/Specs.git'

#inhibit_all_warnings!
use_frameworks!

platform :ios, '9.2'

pod 'PlayKit', :git => 'https://github.com/streamroot/playkit-ios', :branch => 'preferredForwardBufferDuration'
pod 'PlayKitProviders'
pod 'PlayKitKava'

pod 'StreamrootSDK'
  
target 'PlayKitOVPStarter'
