source 'https://github.com/CocoaPods/Specs.git'

#inhibit_all_warnings!
use_frameworks!

platform :ios, '9.2'

pod 'PlayKit'
pod 'PlayKitProviders'
pod 'PlayKitKava'

pod 'StreamrootSDK', '~> 3.12.0'
  
target 'PlayKitOVPStarter'
