# Uncomment the next line to define a global platform for your project

inhibit_all_warnings!

def streamrootPod
  pod 'StreamrootSDK', '~> 3.4.0'
end

target 'DnaSample-iOS' do
  platform :ios, '9.3'
  use_frameworks!

  streamrootPod

end

target 'DnaSample-tvOS' do
 platform :tvos, '10.2'
  use_frameworks!
 
  streamrootPod

end
