# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!

def streamrootPod
   pod 'AVPlayerDNAPlugin'
end

target 'DnaSample-iOS' do
  platform :ios, '10.2'
  use_frameworks!

  streamrootPod
  pod 'GoogleAds-IMA-iOS-SDK',  '3.11.1'
end

target 'DnaSample-tvOS' do
 platform :tvos, '10.2'
  use_frameworks!
 
  streamrootPod

end