source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '10.0'

target 'CustomControls' do
  pod 'Brightcove-Player-Core/dynamic'
  pod 'StreamrootSDK'
end
